### ISSUE TITLE
No defaultMqBindingPort for ndid role,  cause process exit if no MQ_BINDING_PORT set

### ISSUE THREAD

**Issue by bomu-bomu** [ndidplatform/api#16]
from mq.js

```javascript
export const defaultMqBindingPort = (() => {
  if (process.env.ROLE === 'as') return 5557;
  if (process.env.ROLE === 'idp') return 5555;
  if (process.env.ROLE === 'rp') return 5556;
})();
```

If we not set MQ_BINDING_PORT before start process as ndid role,  the process will be crashed with 
```
/home/circleci/project/node_modules/zeromq/lib/index.js:451
  this._zmq.bindSync(addr);
            ^
Error: Invalid argument
    at exports.Socket.Socket.bindSync (/home/circleci/project/node_modules/zeromq/lib/index.js:451:13)
    at Object.<anonymous> (/home/circleci/project/src/mq/index.js:12:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/circleci/project/src/core/rp.js:10:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/circleci/project/src/routes/rp.js:4:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by re7eal** [comment]
Fixed in commit 1de694a
