### ISSUE TITLE
GET /utility/requests/:request_id response with error 500 when request_id does not exist

### ISSUE THREAD

**Issue by re7eal** [ndidplatform/api#19]
```
error: Responded Internal Server Error with HTTP code 500 { responseBody: 
api-idp-1_1  |    { error: 
api-idp-1_1  |       { code: 10000,
api-idp-1_1  |         message: 'Cannot destructure property `special` of \'undefined\' or \'null\'.',
api-idp-1_1  |         stack: 'CustomError: Cannot get request details from blockchain\n    at Object.getRequestDetail (/api/src/tendermint/ndid.js:410:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)\nCaused By: TypeError: Cannot destructure property `special` of \'undefined\' or \'null\'.\n    at Object.getRequestDetail (/api/src/tendermint/ndid.js:396:5)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' } } }
```

**Comment by taneekpet** [comment]
Already fixed at 6eef923, wait for merge.
